server:
  port: 80

spring:
  application:
    name: consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
       defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: consumer80
    prefer-ip-address: true   #健康监控显示ip
