server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10

mybatis:
  type-aliases-package: com.cloud.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql语句
  mapper-locations: classpath:com.cloud.dao/*.xml    #配置mapper文件的位置
eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
       defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: payment8001
    prefer-ip-address: true
